name: Firebase Mirror Temperature

on:
  schedule:
    - cron: "0 */2 * * *"   # setiap 2 jam
  workflow_dispatch:

jobs:
  run-temperature:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"

      - name: Install dependencies
        run: npm install

      - name: Restore serviceAccountKey.json
        env:
          GOOGLE_SERVICE_KEY: ${{ secrets.GOOGLE_SERVICE_KEY }}
        run: |
          echo "$GOOGLE_SERVICE_KEY" > serviceAccountKey.json

      - name: Run temperature mirror
        run: node temp_mirror.cjs
